                        <div class="row">
                            <div class="col">
                                <div id="toolbar" class="btn-toolbar">
                                    <a id="btn_searchILL" class="btn btn-default" href="/cgi-bin/koha/plugins/run.pl?class=Koha%3A%3APlugin%3A%3ACom%3A%3ABM%3A%3ABM_librisill&method=searchILL">
                                        <i class="fa fa-inbox"></i>
                                        Fjärrlåneförfrågningar
                                    </a>
                                    <a id="btn_checkedoutILL" class="btn btn-default" href="/cgi-bin/koha/plugins/run.pl?class=Koha%3A%3APlugin%3A%3ACom%3A%3ABM%3A%3ABM_librisill&method=checkedout_ILL">
                                        <i class="fa fa-list"></i>
                                        Utlånade fjärrlån
                                    </a>
                                    <a id="btn_librisill_requests" class="btn btn-default" href="/cgi-bin/koha/plugins/run.pl?class=Koha%3A%3APlugin%3A%3ACom%3A%3ABM%3A%3ABM_librisill&method=librisill_requests">
                                        <i class="fa fa-download"></i>
                                        Importera fjärrlån (Libris)
                                    </a>
                                    <a id="btn_librisill_incomings_new" class="btn btn-default" href="/cgi-bin/koha/plugins/run.pl?class=Koha%3A%3APlugin%3A%3ACom%3A%3ABM%3A%3ABM_librisill&method=librisill_incomings">
                                        <i class="fa fa-indent"></i>
                                        Nya inkommande fjärrlån (Libris)
                                    </a>
                                    <a id="btn_librisill_incomings_archive" class="btn btn-default" href="/cgi-bin/koha/plugins/run.pl?class=Koha%3A%3APlugin%3A%3ACom%3A%3ABM%3A%3ABM_librisill&method=librisill_incomings&archive=true">
                                        <i class="fa fa-box-archive"></i>
                                        Arkiverade inkommande fjärrlån (Libris)
                                    </a>
                                    <button id="btn_deleted_ill" class="btn btn-default">
                                        <i class="fa fa-trash"></i>
                                        Sök borttagna fjärrlån
                                    </button>
                                </div>
                            </div>
                        </div>